# Generated by Django 4.2.1 on 2023-06-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultData',
            fields=[
                ('consultID', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=100)),
                ('assistName', models.CharField(max_length=100)),
                ('patientRole', models.CharField(max_length=50)),
                ('dateConsult', models.DateField(default='0000-00-00', max_length=140)),
                ('illness', models.CharField(default='Ongoing', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.AutoField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=100)),
                ('empRole', models.CharField(max_length=10)),
            ],
        ),
    ]
