# Generated by Django 4.2.1 on 2023-06-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultdata',
            name='consultID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
