# Generated by Django 4.2.1 on 2023-06-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_consultdata_consultid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('illnessID', models.AutoField(primary_key=True, serialize=False)),
                ('illnessName', models.CharField(max_length=100)),
                ('illnessDesc', models.CharField(max_length=10)),
            ],
        ),
    ]
